### PR TITLE
Add a proper license to the repo

### PR DESCRIPTION
**Pull request by ghost**
The current file in the repo actually leaves the code copyrighted. This PR amends the issue.

### CODE REVIEW

**Comment by valioDOTch** [comment]
Actually it doesn't.
There's no legal requirement in any jurisdiction I am aware of to keep a license in a repo in order to apply it to its content.
Adding the full license text, instead of referencing it is purely a matter of convenience.

**Comment by sylvia43** [comment]
It can't hurt ¯\_(ツ)_/¯

**Comment by jnv** [comment]
It gives you a nice badge in GitHub. That's important!

GH badge

**Comment by superusercode** [comment]
@valioDOTch choosealicense.com says not including the full text leaves it copyrighted, and since GitHub recognizes when the full text is included I assume it is correct.

**Comment by valioDOTch** [comment]
@superusercode Please back your claim with a link.

However it doesn't matter anyway as the statement is wrong AFAIK.

To show why this is merely a matter of convenience and not a legal necessity in any way, just consider the following cases:
* a photographer want to publish their work with a CC-0 license. 
* a musician who publishes their work on Soundcloud with CC-BY
* a vlogger wants to publish their Youtube-Videos with a CC-BY-SA license

In none of these cases adding the full license in a binary form makes any difference (e.g. it doesn't make any sense to include this as metadata within the media files or whatever). What does make a difference is that they have to provide a reference to the license when they publish those works.

**Pull request merged**
